language: java
script: "mvn cobertura:cobertura"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

mvn test -B
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email: false

sudo: false # faster builds

after_success:
bash <(curl -s https://codecov.io/bash) -t 403319bc-0c1a-406c-8987-44e297c7a964
